app/models.py
from  app import db
from  werkzeug.security import generate_password_hash,check_password_hash
from  flask_login import  UserMixin
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from  flask import current_app



class User(db.Model,UserMixin):
    __tablename__='users'
    id=db.Column(db.INTEGER,primary_key=True)
    name=db.Column(db.String(32))
    email=db.Column(db.String(64))
    password_hash=db.Column(db.String(128))
    # 代表用户是否激活
    confirmed=db.Column(db.Boolean,default=False)

    # 生成token,发送邮件验证使用
    def generate_token(self):
        s = Serializer(current_app.config['SECRET_KEY'],expires_in=60)
        token = s.dumps({"id":self.id})
        return token

    def check_token(self,token):
        s = Serializer(current_app.config['SECRET_KEY'])
        try:
            data=s.loads(token)
        except:
            return False
        id=data.get('id')
        if id is None:
            return False
        if id!=self.id:
            return False

        self.confirmed = True;
        # db.session.add(self)
        db.session.commit()
        return True


    @property
    def password(self):
        return  AttributeError('password can not read')

    @password.setter
    def password(self,password):
        self.password_hash=generate_password_hash(password)

    def check_password(self,password):
        return check_password_hash(self.password_hash,password)

# user=User(name='benjamin')
# user.password='123456'
# user.check_password('123456')==>True
# user.check_password('1236')==>False


class HeadTeacher(db.Model):
    __tablename__='headteachers'
    id=db.Column(db.INTEGER,primary_key=True)
    age=db.Column(db.INTEGER,default=24)
    name=db.Column(db.String(32))

class Student(db.Model):
    __tablename__='students'
    id=db.Column(db.INTEGER,primary_key=True)
    age=db.Column(db.INTEGER,default=24)
    name=db.Column(db.String(32))
    teacher_id=db.Column(db.INTEGER,db.ForeignKey('teachers.id'))



class Teacher(db.Model):
    __tablename__='teachers'
    id=db.Column(db.INTEGER,primary_key=True)
    age = db.Column(db.INTEGER, default=44)
    name=db.Column(db.String(32))
    students=db.relationship('Student',backref='teacher')

app/__init__.py
from flask import  Flask
from config import config
from flask_sqlalchemy import SQLAlchemy
from flask_mail import Mail
from flask_bootstrap import  Bootstrap
from flask_moment import Moment
from flask_login import  LoginManager

#这个变量必须叫做moment和bootstrap
moment=Moment()
bootstrap=Bootstrap()
mail=Mail()
db = SQLAlchemy()
login_manager=LoginManager()
login_manager.login_view='auth.login'
login_manager.session_protection='strong'

def create_app(config_name):
    app=Flask(__name__)
    app.config.from_object(config[config_name])

    moment.init_app(app)
    bootstrap.init_app(app)
    mail.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)


    # db.create_all()
    #注册蓝图
    from .main import main as main_bp
    from  .auth import auth as auth_bp
    app.register_blueprint(main_bp)
    app.register_blueprint(auth_bp,url_prefix='/auth')
    #绑定app
    return app

app/main/__init__.py
from flask import  Blueprint
from flask_sqlalchemy import  SQLAlchemy
main=Blueprint("main",__name__)
from . import views,errors

app/main/views.py
from . import  main
from flask import render_template,request,abort
from flask_login import login_required
from app.models import User


@main.route("/",methods=['GET','POST'])
def index():
    info=u'欢迎个锤子'
    return render_template('main/index.html',info=info)


@main.route('/user_info')
@login_required
def user_info():
    id=request.args.get('id')
    if id is None:
        abort(404)
    user=User.query.get(int(id))
    if user is None:
        abort(404)
    return render_template('main/user_info.html', user=user)

@main.app_errorhandler(404)
def errorhandler_404(e):
    return render_template('error/404.html')

@main.app_errorhandler(500)
def errorhandler_500(e):
    return render_template('error/500.html')

app/templates/base.html
{% extends "bootstrap/base.html" %}
{% block title %}
社区管理
{% endblock %}
{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse"
            data-target=".navbar-collapse">
                <span class="sr-only"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">博客站</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/">主页</a> </li>
                 <li><a href="/">社区</a> </li>
            </ul>
             <ul class="nav navbar-nav navbar-right">
                 {% if current_user.is_authenticated %}
                    <li><a  href="{{url_for('main.user_info',id=current_user.id)}}">{{current_user.name}}</a> </li>
                    <li><a href="/">管理中心</a> </li>
                    <li><a href="{{url_for('auth.logout')}}">注销</a> </li>
                 {% endif %}

                  {% if not current_user.is_authenticated %}
                    <li><a  href="{{url_for('auth.login')}}">登录</a> </li>
                    <li><a href="{{url_for('auth.register')}}">注册</a> </li>
                   {% endif %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}
{% block content %}
<div class="container">
    <div class="page-header">
        {% block page_content %}
        {% endblock %}
    </div>

</div>
{% endblock %}

app/templates/main/index.html
{% extends "base.html" %}
{% block page_content %}
<h1>{{ info }}</h1>
{% endblock %}

app/templates/main/user_info.html
{% extends "base.html" %}
{% block page_content %}
<h1>欢迎{{ current_user.name }}来访{{user.name}}的空间</h1>
{% endblock %}